### PR TITLE
OWNERS: add d4s to reviewers

### PR DESCRIPTION
**Pull request by cgwalters**
He did a lot of work on signing and will continue that.

### CODE REVIEW

**Comment by jlebon** [comment]
/approve

I guess we need to wait until @d4s accepts the org invite! :)

**Comment by cgwalters** [comment]
Oops right, just sent that invite.

**Comment by d4s** [comment]
Thank you! Invite has been accepted.
Is there any other action from my side required?

**Comment by jlebon** [comment]
I think that should do the trick!

/verify-owners
/lgtm

**Comment by d4s** [comment]
@jlebon done

**Comment by d4s** [comment]
/lgtm
just testing ;)

**Pull request merged**
