### PR TITLE
repo: NUL terminate readlinkat result

### PR DESCRIPTION
**Pull request by cgwalters**
Coverity was correctly complaining about this.

### CODE REVIEW

**Review by jmarrero — APPROVED** [review]
lgtm

**Comment by cgwalters** [comment]
> [2024-07-29T20:17:00.672Z] Jul 29 20:16:54 qemu0 kola-runext-itest-payload-link.sh[2604]: error: Writing content object: invalid data size for b8/2d4be21c54d26d7042b759c186b18e3e8e508d1ff43d9ee47e8fc6e9bef471.payload-link

Hmm...

**Comment by cgwalters** [comment]
Hah of course, I put the `-1` *inside* the `sizeof` expression...

- Fixed that
- Added a unit test to more quickly debug payload-link issues in the future
- Added the found/expected size to the error

**Review by ericcurtin — APPROVED** [review]

**Comment by jlebon** [comment]
/test fcos-e2e

CI was failing on https://github.com/openshift/os/issues/1551 which should be fixed now.

**Review by jlebon — APPROVED** [review]

**Comment by jmarrero** [comment]
New hit with this patch:
```
1. Defect type: OVERRUN
16. libostree-2024.7/src/libostree/ostree-repo-commit.c:823:7: overrun-buffer-arg: Overrunning array "target_checksum" of 65 bytes by passing it to a function which accesses it at byte offset 258 using argument "size" (which evaluates to 259). [Note: The source code implementation of the function has been overridden by a builtin model.] 
```

**Comment by cgwalters** [comment]
:arrow_right: https://github.com/ostreedev/ostree/pull/3284

**Pull request merged**
