### PR TITLE
cci: Update for buildroot changes

### PR DESCRIPTION
**Pull request by cgwalters**
See latest in https://github.com/coreos/fedora-coreos-tracker/blob/master/docs/ci-and-builds.md

### CODE REVIEW

**Comment by jlebon** [comment]
Hmm, bunch of failures and for some reason it's not archiving `test-suite.log`. Try inlining a `cat test-suite.log` maybe?

**Comment by cgwalters** [comment]
OK yeah I should have immediately pulled the buildroot image and run the same commands locally; being able to trivially do so is a huge point of all of this.

The failure was then obvious: https://github.com/coreos/fedora-coreos-config/pull/911

**Comment by cgwalters** [comment]
Well, that's just exciting:

```
       Message: Process 570832 (mv) of user 100999 dumped core.
                
                Stack trace of thread 57473:
                #0  0x00007f242b809442 __read (libc.so.6 + 0xf2442)
                #1  0x00007f242b79a122 _IO_file_underflow@@GLIBC_2.2.5 (libc.so.6 + 0x83122)
                #2  0x00007f242b78e1b8 __getdelim (libc.so.6 + 0x771b8)
                #3  0x000055a8af2c52ad yesno (/usr/bin/mv + 0x92ad)
                #4  0x000055a8af2c99b6 copy_internal (/usr/bin/mv + 0xd9b6)
                #5  0x000055a8af2cd133 do_move (/usr/bin/mv + 0x11133)
                #6  0x000055a8af2c09be main (/usr/bin/mv + 0x49be)
                #7  0x00007f242b73f1e2 __libc_start_main (libc.so.6 + 0x281e2)
                #8  0x000055a8af2c0c0e _start (/usr/bin/mv + 0x4c0e)
```

**Comment by cgwalters** [comment]
OK one thing going on here is I think ye olde umask bug - we're suddenly triggering `mv` to warn about replacing existing files;
```
++ mv ostree-srv/gnomerepo/objects/6d/8ddc0347c6bdf6494972713cee589ad760449b3495f2957f60f58c6900f8e3.commitmeta.bak ostree-srv/gnomerepo/objects/6d/8ddc0347c6bdf6494972713cee589ad760449b3495f2957f60f58c6900f8e3.commitmeta
mv: replace 'ostree-srv/gnomerepo/objects/6d/8ddc0347c6bdf6494972713cee589ad760449b3495f2957f60f58c6900f8e3.commitmeta', overriding mode 0000 (---------)? +++ run_exit_cmds
```

I may try to just hack in a umask again here and *not* dive into figuring out where umask is really coming from...

**Comment by cgwalters** [comment]
OK I think I understand one major problem - we're now running the build and tests in the workspace instead of the `/srv` emptydir.  Or at least I'm pretty sure in Jenkins we were doing builds in `/srv` before.  At least locally with podman I definitely have ostree issues interacting with `fuse-overlayfs` (it's also slooooow).

**Comment by jlebon** [comment]
> OK I think I understand one major problem - we're now running the build and tests in the workspace instead of the `/srv` emptydir. Or at least I'm pretty sure in Jenkins we were doing builds in `/srv` before. At least locally with podman I definitely have ostree issues interacting with `fuse-overlayfs` (it's also slooooow).

cosa builds are done in `/srv`, but there shouldn't be any changes to component builds (it was built in the workspace before too).

**Comment by jlebon** [comment]
> [2021-03-26T22:54:14.751Z] gawk: cmd. line:392: (FILENAME=- FNR=2) fatal: cannot open pipe `cat >&3' for output: Cannot allocate memory

Hmm, that's odd. There's no difference between `cosaPod` and `buildPod` wrt memory requests, but I guess... let's try bumping the memory request to e.g. 3Gi?

**Comment by jlebon** [comment]
Ohh one major difference is that `cosaPod` uses `dumb-init` but not `buildPod`. Hmm, yeah we should definitely do that:
- https://github.com/coreos/fedora-coreos-config/pull/916
- https://github.com/coreos/coreos-ci-lib/pull/69

**Comment by jlebon** [comment]
(Restarted CI here now that we have `dumb-init`.)

**Comment by cgwalters** [comment]
OK yeah that's working *much* better.  I see a missing `python3-pyyaml` dep; testing a fix and validating we're not missing anything else.

**Comment by jlebon** [comment]
Hmm, not clear what went wrong here. It looks like `read line` failed somehow. Maybe try that `make -C tests/kolainst install DESTDIR=...` invocation locally in the buildroot container?

**Comment by cgwalters** [comment]
Hooray!  CI is passing here.

**Pull request merged**
