### PR TITLE
[merged] libglnx porting: Use of GSDirFdIterator

### PR DESCRIPTION
**Pull request by cgwalters**
This one was pretty simple.  One of the uses in `repo.c` was just a
leftover variable.

### CODE REVIEW

**Comment by cgwalters** [comment]
:construction: I only tested the first commit, haven't done the second yet.

**Comment by jlebon** [comment]
@cgwalters Is this ready for review?

**Comment by cgwalters** [comment]
Yeah, should be.  I still need to hand test the journal bits though.

**Comment by cgwalters** [comment]
Tested the journal bits, works.

**Comment by jlebon** [comment]
@rh-atomic-bot r+ 2e0a6db

**Pull request closed without merging**
