### PR TITLE
Rework OstreeAsyncProgress API to use GVariant

### PR DESCRIPTION
**Pull request by pwithnall**
I spent a little while today looking at different progress reporting APIs, and it turns out that despite @cgwalters’ reservations, `OstreeAsyncProgress` is pretty much ideal. I’ve pasted my analysis at the bottom of this PR.

This PR adds a few missing features to `OstreeAsyncProgress` which will allow it to be used by the LAN/USB work (PR #782) to give structured information about each ref it’s pulling, for example, by passing `GVariant` dicts in the progress information.

The PR also improves the atomicity of accesses to an `OstreeAsyncProgress` instance, which fixes some potential bugs in reporting inconsistent pull progress.

---

Options for progress reporting:
 * `EvPrintOperation`: have an object for the entire operation, report progress via its properties or methods
   - \+ Nicely encapsulates the lifetime of the operation (can be queried after the operation finishes)
   - − Properties aren’t threadsafe
   - \+ Easily extensible
   - \+ Typesafe
   - \+ Supports notification (notify signal)
   - − Not a standard interface (a new object has to be implemented for each operation)
   - − Queries are not atomic (different properties queried at different times)
 * `FlatpakProgressCallback`, `GFileProgressCallback`: caller provides a callback which has a fixed set of parameters
   - − Doesn’t encapsulate the lifetime of the operation (can’t be queried afterwards)
   - \+ Threadsafe
   - − Not extensible
   - \+ Supports notification (the callback itself)
   - \+ State can be queried atomically (all properties are returned atomically)
   - \+ Standard interface
   - \+ Typesafe
 * `OstreeAsyncProgress`: caller provides an object which has a notification callback associated with it
   - \+ Fairly well encapsulates the lifetime of the operation (can be queried after the operation finishes)
   - \+ Threadsafe
   - \+ Easily extensible (though more complex types are a bit of a pain)
   - − Not typesafe (relies on documentation), but subclasses can add type safety
   - \+ Supports notification (callback)
   - \+ Standard interface
   - − Queries are not atomic (different properties queried at different times), but this could be fixed easily

### CODE REVIEW

**Comment by cgwalters** [comment]
The flatpak failure isn't your fault, I submitted a PR to fix it.

The travis one though looks real:
`../src/libostree/ostree-async-progress.c:148:3: error: implicit declaration of function 'g_autoptr' [-Werror=implicit-function-declaration]`

I think we just need an `#include "libglnx.h"`.

Otherwise: Awesome!  A++, would review again!

**Comment by cgwalters** [comment]
@rh-atomic-bot r+  	08d4a98

**Comment by dbnicholson** [comment]
I'm hitting an assertion with this:
```
$ ostree --repo=test pull build app/org.gnome.Gnote/x86_64/eos3

**
OSTree:ERROR:src/libostree/ostree-async-progress.c:214:ostree_async_progress_get: assertion failed: (variant != NULL)
Aborted (core dumped)
```
This seems to happen from `ostree_async_progress_finish` when nothing has actually been pulled because I already have the commit. It emits the changed signal even though nothing's changed. Then the `ostree_async_progress_get` in `ostree_repo_pull_default_console_progress_changed` blows up because there's no data in the hash table. Here's the backtrace:
```
#0  0x00007ffff671fce7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff67213d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6dd8355 in g_assertion_message (domain=domain@entry=0x7ffff79a0e3c "OSTree", file=file@entry=0x7ffff79a0eb0 "src/libostree/ostree-async-progress.c", line=line@entry=214, func=func@entry=0x7ffff79a0f50 <__func__.25193> "ostree_async_progress_get", message=message@entry=0x7b4710 "assertion failed: (variant != NULL)") at /usr/src/packages/BUILD/glib2.0-2.50.2+dev22.0cb2266/./glib/gtestutils.c:2432
#3  0x00007ffff6dd83ea in g_assertion_message_expr (domain=domain@entry=0x7ffff79a0e3c "OSTree", file=file@entry=0x7ffff79a0eb0 "src/libostree/ostree-async-progress.c", line=line@entry=214, func=func@entry=0x7ffff79a0f50 <__func__.25193> "ostree_async_progress_get", expr=expr@entry=0x7ffff79a0e65 "variant != NULL") at /usr/src/packages/BUILD/glib2.0-2.50.2+dev22.0cb2266/./glib/gtestutils.c:2455
#4  0x00007ffff7954bfe in ostree_async_progress_get (self=0x641140 [OstreeAsyncProgress]) at src/libostree/ostree-async-progress.c:214
#5  0x00007ffff7962ebd in ostree_repo_pull_default_console_progress_changed (progress=0x641140 [OstreeAsyncProgress], user_data=0x5fad) at src/libostree/ostree-repo.c:3734
#6  0x00007ffff708c224 in _g_closure_invoke_va (closure=0x5fad, closure@entry=0x64d450, return_value=0x5fad, return_value@entry=0x0, instance=0x6, instance@entry=0x641140, args=0x7ffff671fce7 <__GI_raise+55>, args@entry=0x7fffffffda30, n_params=0, param_types=0x7b4d90) at /usr/src/packages/BUILD/glib2.0-2.50.2+dev22.0cb2266/./gobject/gclosure.c:867
#7  0x00007ffff70a6747 in g_signal_emit_valist (instance=0x641140, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffda30) at /usr/src/packages/BUILD/glib2.0-2.50.2+dev22.0cb2266/./gobject/gsignal.c:3300
#8  0x00007ffff70a70bf in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at /usr/src/packages/BUILD/glib2.0-2.50.2+dev22.0cb2266/./gobject/gsignal.c:3447
#9  0x000000000041b50c in ostree_builtin_pull (argc=3, argv=0x7fffffffde18, cancellable=0x0, error=0x7fffffffdcc0) at src/ostree/ot-builtin-pull.c:323
#10 0x000000000041306e in ostree_run (argc=4, argv=0x7fffffffde18, commands=0x62c1c0 <commands>, res_error=0x7fffffffdd10) at src/ostree/ot-main.c:200
#11 0x000000000040a9dc in main (argc=5, argv=0x7fffffffde18) at src/ostree/main.c:78
```

**Comment by pwithnall** [comment]
I can’t reproduce the exact crash you’re seeing, but I think I can see where the problem is. ⇒ #835.

**Pull request closed without merging**
