### PR TITLE
tests: Don't follow symlinks for payload-link test

### PR DESCRIPTION
**Pull request by cgwalters**
Or things become recursive ∞.  Noticed this start breaking in a
recent PR.

### CODE REVIEW

**Comment by giuseppe** [comment]
hm.. still I am not sure how this could be recursive, find should not follow symlinks.  In any case, the amount of logging generated is way too much

**Comment by giuseppe** [comment]
bot, retest this please

**Comment by cgwalters** [comment]
Yeah, I think you're right, it was the sha256 that was a bit slow and had me thinking we were recursing.  I reworked the PR again, let's see?  :arrow_up:

**Comment by giuseppe** [comment]
it seems the tests are still not running, but the patch LGTM

**Comment by jlebon** [comment]
LGTM too. Tests are not being triggered automatically currently. Will fire it off manually.
@rh-atomic-bot r=giuseppe dc03fb1

**Pull request closed without merging**
