### PR TITLE
deploy: Fix removing /var/.updated with separate /var mount

### PR DESCRIPTION
**Pull request by cgwalters**
There's some subtlety to this, we don't handle all cases.
But the 99% cases are using `--sysroot deploy` to create an
initial deployment, and then doing upgrades from inside
a booted deployment.

It was only the latter case that didn't work with a separate `/var`.
Fixing all of them would probably require libostree to learn
how to e.g. look at `/etc/fstab` (or worse, systemd mount units?)
and handle the mounting.  I don't think we want to do anything
like that right now, since there are no active drivers for the
use case.

Closes: https://github.com/ostreedev/ostree/issues/1729

### CODE REVIEW

**Comment by cgwalters** [comment]
Just compile/unit tested, but sadly our test suite today doesn't actively exercise split `/var`.

**Comment by akiernan** [comment]
LGTM

```
root@hvt-341:~# ls -l /var/.updated
-rw-r--r-- 1 root root 190 Jan  1  1970 /var/.updated
root@hvt-341:~# ostree admin deploy master/nano/nano2/nano-image-osa
Copying /etc changes: 4 modified, 0 removed, 15 added
[  164.911751] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
warning: Failed to remount /boot read-only: Device or resource busy
Transaction complete; bootconfig swap: yes; deployment count change: 0
Freed objects: 600.9 kB
root@hvt-341:~# ls -l /var/.updated
ls: cannot access '/var/.updated': No such file or directory
```

**Comment by cgwalters** [comment]
@rh-atomic-bot delegate=akiernan

**Comment by akiernan** [comment]
@rh-atomic-bot r+ f787f66e9300ba89da7bfdcc96c7098a51c7fc2b

**Pull request closed without merging**
