### PR TITLE
[merged] Prune with parents

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Comment by cgwalters** [comment]
Note: I did manually verify the test case failed without the patch.

**Comment by cgwalters** [comment]
Travis failure looks to be the ongoing unknown race in pulls.

**Comment by jlebon** [comment]
Nice! @rh-atomic-bot r+ 8185441

**Comment by jlebon** [comment]
@rh-atomic-bot r+ 5f3dd5a

**Comment by jlebon** [comment]
OK, I think I was able to reproduce the Travis failure here. Though I haven't yet found a good reproducer (I just ran `make check TESTS=tests/test-pull-repeated.sh` in a loop inside a debian:jessie container).

```
Core was generated by `ostree --repo=repo pull --mirror origin main'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f9e4e2c32e5 in g_mutex_lock (mutex=mutex@entry=0x6666666666666666) at /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gthread-posix.c:1337
1337    /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gthread-posix.c: No such file or directory.
(gdb) t a a bt

Thread 2 (Thread 0x7f9e4fcf3880 (LWP 25255)):
#0  0x00007f9e4f0774db in pthread_join (threadid=140317828732672, thread_return=thread_return@entry=0x0) at pthread_join.c:92
#1  0x00007f9e4e2c3347 in g_system_thread_wait (thread=0x11bbca0) at /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gthread-posix.c:1218
#2  0x00007f9e4e2a5c95 in g_thread_join (thread=0x11bbca0) at /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gthread.c:928
#3  0x00007f9e4ee419d9 in _ostree_fetcher_finalize (object=0x1193360) at ../src/libostree/ostree-fetcher.c:575
#4  0x00007f9e4e55926a in g_object_unref (_object=0x1193360) at /build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gobject.c:3170
#5  0x00007f9e4ee174eb in ostree_repo_pull_with_options (self=0x1190000, remote_name_or_baseurl=0x11bc080 "origin", options=0x1193610, progress=0x0, cancellable=0x0, error=0x7ffc6b3275d8)
    at ../src/libostree/ostree-repo-pull.c:3026
#6  0x0000000000420ac9 in ostree_builtin_pull (argc=3, argv=0x7ffc6b327748, cancellable=0x0, error=0x7ffc6b3275d8) at ../src/ostree/ot-builtin-pull.c:260
#7  0x0000000000415740 in ostree_run (argc=5, argv=0x7ffc6b327748, commands=0x637300 <commands>, res_error=0x7ffc6b327640) at ../src/ostree/ot-main.c:209
#8  0x000000000040b4d5 in main (argc=6, argv=0x7ffc6b327748) at ../src/ostree/main.c:78

Thread 1 (Thread 0x7f9e4a565700 (LWP 25256)):
#0  0x00007f9e4e2c32e5 in g_mutex_lock (mutex=mutex@entry=0x6666666666666666) at /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gthread-posix.c:1337
#1  0x00007f9e4e27c1b8 in g_source_destroy_internal (source=0x14aec60, context=0x6666666666666666, have_lock=0) at /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gmain.c:1159
#2  0x00007f9e4e27c8d5 in g_source_destroy (source=<optimized out>) at /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gmain.c:1227
#3  0x00007f9e4eb80ca8 in soup_session_dispose (object=0x11a4110) at soup-session.c:309
#4  0x00007f9e4e5591f5 in g_object_unref (_object=0x11a4110) at /build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gobject.c:3133
#5  0x00007f9e4ee4177c in ostree_fetcher_session_thread (data=0x11bb0f0) at ../src/libostree/ostree-fetcher.c:514
#6  0x00007f9e4e2a5845 in g_thread_proxy (data=0x11bbca0) at /build/glib2.0-y6934K/glib2.0-2.42.1/./glib/gthread.c:764
#7  0x00007f9e4f0760a4 in start_thread (arg=0x7f9e4a565700) at pthread_create.c:309
#8  0x00007f9e4dcc987d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

For reference, `src/libostree/ostree-fetcher.c:514` refers to the fetcher thread clearing up the SoupSession:

```C
 506   g_main_loop_run (closure->main_loop);                                          
 507                                                                                  
 508   /* Since the ThreadClosure may be finalized from any thread we                 
 509    * unreference all data related to the SoupSession ourself to ensure           
 510    * it's freed in the same thread where it was created. */                      
 511   g_clear_pointer (&closure->outstanding, g_hash_table_unref);                   
 512   while (!g_queue_is_empty (&closure->pending_queue))                            
 513     g_object_unref (g_queue_pop_head (&closure->pending_queue));                 
 514   g_clear_pointer (&closure->session, g_object_unref);                           
 515                                                                                  
 516   thread_closure_unref (closure);                                                
 517                                                                                  
 518   /* Do this last, since libsoup uses g_main_current_source() which              
 519    * relies on it.                                                               
 520    */                                                                            
 521   g_main_context_pop_thread_default (mainctx);                                   
 522                                                                                  
 523   return NULL;                                                                   
 524 }                                                         
```

It seems like libsoup is calling `g_source_destroy_internal()` with a bogus context, though from looking a bit at the source, it's not clear whether it's a bug in libsoup or something we're doing wrong in our interaction with it.

---

Actually, just now I was able to reproduce it on my host proper (with the same backtraces) by forcing ostree to use libsoup-2.48 rather than 2.52. It took about an hour of looping over `tests/test-pull-repeated.sh`. Again, it's not clear whether 2.48 was buggy, or if it just helped triggered some race in the pull code.

**Comment by cgwalters** [comment]
That sounds like the same thing as https://bugzilla.gnome.org/show_bug.cgi?id=768567

**Comment by jlebon** [comment]
Oh yeah, that's exactly it. Blehh, should've checked the issues first. :)

**Pull request closed without merging**
