### PR TITLE
 repo/commit: Support group-writable files for bare-user-only

### PR DESCRIPTION
**Pull request by cgwalters**
These exist in the wild for flatpak, and aren't really a problem.
The canonical permissions are still `0{6,7}44`, we just support
the additional writable bit for the group now to avoid breaking
some flatpak content.

### CODE REVIEW

**Comment by alexlarsson** [comment]
Canonical is 755/644 you mean?

**Comment by cgwalters** [comment]
Yeah, pushed with a reworded commit message.

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+ d313ae

**Comment by cgwalters** [comment]
Pushed fixups :arrow_up:

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+ 4e682b4

**Pull request closed without merging**
