### PR TITLE
Release 2017.13

### PR DESCRIPTION
**Pull request by cgwalters**
We've accumulated a fair bit, time for a new release before we
e.g. try to land the locking PR.

### CODE REVIEW

**Comment by jlebon** [comment]
bot, retest this please

**Comment by jlebon** [comment]
Heh:

```
>>> ci/ci-release-build.sh
*** is_release_build is set to no ***
ERROR: release commit does not have is_release_build=yes
```

Who's a good bot? *You're* a good bot. ✋ 🤖

**Comment by dustymabe** [comment]
> Who's a good bot? You're a good bot. ✋ 🤖

🐶

**Comment by jlebon** [comment]
I squashed the two commits since the bot didn't like the fixup commit changing `is_release_build` but not following the right commit message format!

@rh-atomic-bot r+ ffbb66d

**Comment by jlebon** [comment]
@rh-atomic-bot r+ 8773d55

**Pull request closed without merging**
