### PR TITLE
man/ostree: Document --repo option a bit more

### PR DESCRIPTION
**Pull request by jlebon**
This new information is already mostly part of `ostree.repo(5)`, though
let's put it in `ostree(1)` as well since that's where the switch is
officially documented.

### CODE REVIEW

**Comment by dustymabe** [comment]
will this hit the man page and the `--help` ?

**Comment by puiterwijk** [comment]
That seems like a lot of magic to me, but thanks for documenting.
Note that `ostree pull-local --help` (for example) also doesn't list any of this. Might be useful to add there too: `--repo=PATH                 Path to OSTree repository (defaults to /sysroot/ostree/repo)`

**Comment by jlebon** [comment]
The `ot-main.c` part of the patch should be inherited into the `--help` output of all the commands that have a `--repo` switch.

The XML part is the man page for `ostree`. It's not in the per-command man pages, in the same way e.g. `git -C` is documented in `git(1)`, but not `git-pull(1)`.

**Comment by cgwalters** [comment]
FWIW the rationale for the current behavior is just that we match what git does with bare repositories.

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 2b0a947

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
