### PR TITLE
tree: add .vimrc

### PR DESCRIPTION
**Pull request by jlebon**
This requires the `exrc` option to be turned on.

### CODE REVIEW

**Comment by cgwalters** [comment]
I remembered where `.editorconfig` came from, see
https://github.com/projectatomic/bubblewrap/blob/master/.editorconfig

Mind if I squash a copy of that in and amend the commit message?  (or you can)

**Comment by jlebon** [comment]
Oh that's neat! That's a much cleaner solution.
Sure, go ahead!

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 0d10ccc

**Comment by jlebon** [comment]
@rh-atomic-bot r=cgwalters aad62c8

**Pull request closed without merging**
