### PR TITLE
Release 2018.6

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Comment by alexlarsson** [comment]
bot, retest this please

**Comment by alexlarsson** [comment]
bot, retest this please

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by alexlarsson** [comment]
If this fails too, can we maybe skip the CI just for the release? I'm sort of blocking on this to do a flatpak release.

**Pull request merged**
