### PR TITLE
Min space minor fixes

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Comment by uajain** [comment]
LGTM. Thank you @cgwalters for these follow-up fixes.

**Comment by jlebon** [comment]
Nice follow up!
@rh-atomic-bot r+ 4c298ca

**Comment by jlebon** [comment]
```
+ ostree --repo=mnt/repo pull-local /ostree/repo c51100f14cf12b25c16562cede7455191e536c0534e3b2ef87e66be9e12899ae
error: Invalid min-free-space-size '1T'
```

The one time that test fails that it's *not* a flake. :snowflake: 
I think it needs to be `TB`? (Though we should probably accept both).

**Comment by jlebon** [comment]
Ahh heh, we had the semantics inverted.
@rh-atomic-bot r+ f98f3fb

**Comment by jlebon** [comment]
@rh-atomic-bot r+ 7051ce9

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
