### PR TITLE
ci: Bump flatpak version (and build to f27)

### PR DESCRIPTION
**Pull request by cgwalters**
Just keeping this updated.

### CODE REVIEW

**Comment by cgwalters** [comment]
@alexlarsson Any idea offhand why we wouldn't be finding the icon cache here?

**Comment by alexlarsson** [comment]
There is an optional trigger to rebuild the icon cache, but it needs gtk-update-icon-cache installed. Maybe some dependency changed that caused this to not be installed anymore?

**Comment by cgwalters** [comment]
Got it!  Was missing `hicolor-icon-theme`.  This should be good to go now.

**Comment by jlebon** [comment]
@rh-atomic-bot r+ 3b68820

**Pull request closed without merging**
