### PR TITLE
Release 2017.4

### PR DESCRIPTION
**Pull request by cgwalters**
It's been about a month, and there's a fair amount of stuff already (new APIs, internal cleanup, fixes).  Let's do this before we land more work.

### CODE REVIEW

**Comment by cgwalters** [comment]
Actually I'd like to do https://github.com/ostreedev/ostree/issues/783 first.

**Comment by cgwalters** [comment]
🆕 With fewer syntax ✍ errors!

**Comment by cgwalters** [comment]
Let's do this before we land anything else?

**Comment by jlebon** [comment]
@rh-atomic-bot r+ 10143cd

**Pull request closed without merging**
