### PR TITLE
[merged] ci: Make all ci tests gating for Homu

### PR DESCRIPTION
**Pull request by cgwalters**
See the rhci docs.

### CODE REVIEW

**Comment by jlebon** [comment]
@rh-atomic-bot r+

**Comment by jlebon** [comment]
Hmm, not sure what homu is waiting for here. The `required` status is set: https://github.com/ostreedev/ostree/commits/auto

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by giuseppe** [comment]
@rh-atomic-bot retry

**Comment by jlebon** [comment]
@cgwalters could you check the logs? Seems like it's not seeing the `required` status getting set.

**Comment by cgwalters** [comment]
Hmm, maybe this is 
```
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python3.4/site-packages/homu/server.py", line 414, in github
    report_build_res(info['state'] == 'success', info['target_url'], 'status-' + status_name, state, logger, repo_cfg)
  File "/usr/lib/python3.4/site-packages/homu/server.py", line 424, in report_build_res
    state.set_build_res(builder, succ, url)
  File "/usr/lib/python3.4/site-packages/homu/main.py", line 177, in set_build_res
    self.merge_sha,
  File "/usr/lib/python3.4/site-packages/homu/main.py", line 53, in db_query
    db.execute(*args)
sqlite3.IntegrityError: NOT NULL constraint failed: build_res.url

```
?

**Comment by jlebon** [comment]
Blahh, OK sure: https://github.com/jlebon/redhat-ci/commit/4873ace
Shouldn't take too long to roll out: https://hub.docker.com/r/jlebon/redhat-ci/builds/

**Comment by jlebon** [comment]
I also opened https://github.com/servo/homu/issues/69.

Should be good to go now, let's try it again!
@rh-atomic-bot retry

**Pull request closed without merging**
