### PR TITLE
pull: Don't save summary to cache before validating signatures

### PR DESCRIPTION
**Pull request by alexlarsson**
In case of some kind of race or other weirdness we might be getting
non-matching versions of summary.sig and summary, where summary.sig
is the latest version. Currently we're saving them to the cache
directly after downloading them successfully, but they will then fail
to gpg validate. Then on the next run we'll keep using the cached files
even if they are incorrect, until summary.sig changes upstream.

This changes the order so that we verify the signatures before saving
to the cache, thus ensuring that we don't end up in a stuck state.

Fixes https://github.com/ostreedev/ostree/issues/1523

### CODE REVIEW

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ abcdeab6

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ abdeab6

**Comment by alexlarsson** [comment]
I think CI is broken because 0001-Don-t-write-to-parent-repo.patch was backported to fedora.

**Comment by cgwalters** [comment]
https://github.com/ostreedev/ostree/pull/1530

**Comment by alexlarsson** [comment]
@rh-atomic-bot retest

**Comment by alexlarsson** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
