### PR TITLE
pull: Use GNU coding style

### PR DESCRIPTION
**Pull request by dbnicholson**

### CODE REVIEW

**Comment by jlebon** [comment]
Thanks!
/lgtm

**Comment by dbnicholson** [comment]
It looks like this got blocked because the test suite failed on jenkins. As far as I can tell from [test-suite.log](https://jenkins-coreos-ci.apps.ocp.ci.centos.org/job/github-ci/job/ostreedev/job/ostree/job/PR-2254/1/artifact/test-suite.log) it was killed:
```
ERROR: tests/test-repo-finder-config
====================================
...
./buildutil/tap-test: line 27: 49397 Killed                  timeout --kill-after=60 --signal=ABRT $(( 600 * ${TEST_TIMEOUT_FACTOR:-1} )) ${srcd}/${bn} -k --tap
```
I doubt my coding style change caused the test to fail (and the tests pass locally).

**Comment by jlebon** [comment]
I restarted CI. (You should be able to do that too BTW by logging into Jenkins and clicking the "loop" icon in the top right.)

**Pull request merged**
