### PR TITLE
ostree_repo_resolve_rev: Resolve refs set in the transaction

### PR DESCRIPTION
**Pull request by alexlarsson**
This allows you to get at the current commit for a ref pending in the transaction.

This fixes: https://github.com/ostreedev/ostree/issues/1623, and i'd like to (eventually) use this in flatpak.

### CODE REVIEW

**Comment by alexlarsson** [comment]
Its not exactly clear to me why/how the FAH28-insttest test failed, any help?

**Comment by cgwalters** [comment]
Yeah, I don't see the problem there either, it's unfortunately been flaky.

@rh-atomic-bot r+ 4a002d2

**Comment by alexlarsson** [comment]
@rh-atomic-bot retry

**Comment by alexlarsson** [comment]
```
Trying to pull repository registry.fedoraproject.org/fedora ... 
/usr/bin/docker-current: pinging docker registry returned: Get https://registry.fedoraproject.org/v2/: EOF.
```
and
```
fatal: [/srv/code/tests/installed/fedora-atomic-host.qcow2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh_exchange_identification: Connection closed by remote host\r\n", "unreachable": true}
	to retry, use: --limit @/srv/code/tests/installed/destructive-unit.retry
```

Seems like network flapping to me.

**Comment by alexlarsson** [comment]
@rh-atomic-bot retry

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
