### PR TITLE
[merged] We started testing docs, and you wouldn't believe what happened next!

### PR DESCRIPTION
**Pull request by cgwalters**
Made you click!

### CODE REVIEW

**Comment by giuseppe** [comment]
X-Spam-Status: No, score=2.2 required=5.0
not as high as I imagined :)

LGTM with the additional '\n' in a6a8c4c

**Comment by cgwalters** [comment]
fixup! :arrow_up:

**Comment by giuseppe** [comment]
@cgwalters-bot r+ a515df0

**Comment by cgwalters** [comment]
Hm, looks like the Docker image started getting write access to `/dev/fuse` for some reason.

**Comment by cgwalters** [comment]
@cgwalters-bot retry

**Pull request closed without merging**
