### PR TITLE
[merged] unlock: Fix description for --hotfix

### PR DESCRIPTION
**Pull request by cgwalters**
Came up during an IRC discussion.  The text is accurate but
not very helpful.

### CODE REVIEW

**Comment by dustymabe** [comment]
LGTM

**Comment by cgwalters** [comment]
@rh-atomic-bot delegate=dustymabe

**Comment by dustymabe** [comment]
@rh-atomic-bot r+

**Comment by dustymabe** [comment]
btw, i almost wonder if `hotfix` shouldn't be `persistent` instead

**Pull request closed without merging**
