### PR TITLE
travis: Add a 32 bit build

### PR DESCRIPTION
**Pull request by cgwalters**
In the past we've had 32 bit bugs that were caught by
the compiler, let's add this to Travis.

### CODE REVIEW

**Comment by cgwalters** [comment]
Motivated by looking at https://bugzilla.redhat.com/show_bug.cgi?id=1888436

**Comment by jlebon** [comment]
/lgtm
though Travis looks unhappy.

**Comment by jlebon** [comment]
Ahh, missing a
/hold cancel

**Pull request merged**
