### PR TITLE
lib/repo-commit: Abort a transaction if preparing it fails

### PR DESCRIPTION
**Pull request by pwithnall**
If ostree_repo_prepare_transaction() fails, we should reset the
repository’s state so that the failed call was essentially idempotent.
Do that by calling ostree_repo_abort_transaction() on the failure path.

Typically, the way for preparing a transaction to fail is for its
GCancellable to be triggered, rather than because any of the operations
involved in preparing a transaction are particularly failure prone.

Signed-off-by: Philip Withnall <withnall@endlessm.com>

### CODE REVIEW

**Comment by pwithnall** [comment]
The [test failure](https://s3.amazonaws.com/aos-ci/ghprb/ostreedev/ostree/02b2f20849d441e4b4ff72c9a79097346407c9ef.1530026445736796672/output.log) seems to be unrelated:
```
TASK [Load status json] ********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "rpm-ostree status --json", "msg": "[Errno 2] No such file or directory", "rc": 2}
	to retry, use: --limit @/var/tmp/checkout/tests/installed/nondestructive.retry
```

**Comment by cgwalters** [comment]
> The test failure seems to be unrelated:

Yep, just fixed that.  Hmm, wouldn't it work to just create an `g_autoptr(_OstreeRepoAutoTransaction) txn` here, and set it to NULL at the end of the success path?

**Comment by pwithnall** [comment]
> Hmm, wouldn't it work to just create an g_autoptr(_OstreeRepoAutoTransaction) txn here, and set it to NULL at the end of the success path?

Ah, good suggestion!

**Comment by cgwalters** [comment]
I don't have notifications when one pushes to a PR, so please do add an "Updated" or so comment when you update the PR.  Thanks for the patch!

@rh-atomic-bot r+ ed82835

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
