### PR TITLE
Update libglnx to get g_autoptr backports

### PR DESCRIPTION
**Pull request by mwleeds**

### CODE REVIEW

**Comment by jlebon** [comment]
> error: Commit message for 18598193d372a57a3d5fd0b9ed964c3f4be00cdd changes a submodule, but does not match regex Update submodule: libglnx

Ahh yes. You'll want to add: "Update submodule: libglnx" to the commit message to convince the bot you really meant to update a submodule. :) We've had issues in the past where PRs accidentally altered submodules.

**Comment by jlebon** [comment]
@rh-atomic-bot r+ af72e87

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by ebassi** [comment]
After this landed, GNOME Continuous breaks during check out:

```
Cloning into 'libglnx'...
fatal: reference is not a tree: e1a78cf2f5351d5394ccfb79f3f5a7b4917f73f3
Unable to checkout 'e1a78cf2f5351d5394ccfb79f3f5a7b4917f73f3' in submodule path 'libglnx'
```

**Comment by cgwalters** [comment]
Probably a race between the resolve/build steps, should (hopefully) fix itself next cycle.  Ping if not.

**Comment by ebassi** [comment]
A point made by @alexlarsson: the Git submodule for libglnx still points to git.gnome.org, and some versions of Git do not really like redirects.

**Pull request closed without merging**
