### PR TITLE
tests: fix admin upgrade timestamp file check

### PR DESCRIPTION
**Pull request by jlebon**
In #1055, I tried to be helpful but that didn't work out all too well.
We need to recompute the file path since one is in archive mode and the
other in bare mode.

### CODE REVIEW

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ b07b2bb

**Comment by cgwalters** [comment]
FWIW I did manually test that the tests *fail* when I commented out the `timestamp-check` bit in the upgrader.  I do find myself wondering a lot about solving the "test the tests" problem...

**Comment by jlebon** [comment]
And of course, my fix itself was wrong. Tested to work this time. ⬆️
Apologies for the kerfuffle.

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 9b49075

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
