### PR TITLE
lib/pull: Two cosmetic internal function renames

### PR DESCRIPTION
**Pull request by cgwalters**
I'm mainly doing this to sanity check the CI state right now.

However, I also want to more cleanly/clearly distinguish
the "sign" code from the "gpg" code.

Rename one function to include `gpg`.

For the other...I think what it's really doing is using the remote
config, so change it to include `remote` in its name.

### CODE REVIEW

**Comment by cgwalters** [comment]
OK yeah, something fell over in coreosci I think...but I simply cannot see what's wrong from looking at the Jenkins UI.  I just logged into the cluster and it looks like the relevant pods have already been GC'd.

**Comment by cgwalters** [comment]
Ahh wait I see, looking at the legacy UI it's clear: https://jenkins-coreos-ci.apps.ci.centos.org/job/github-ci/job/ostreedev/job/ostree/view/change-requests/job/PR-2068/1/console

`groovy.lang.MissingPropertyException: No such property: cosaDir for class: org.codehaus.groovy.runtime.GStringImpl`

So this is likely fallout from groovy.lang.MissingPropertyException: No such property: cosaDir for class: org.codehaus.groovy.runtime.GStringImpl

**Comment by jlebon** [comment]
Yup, sorry about that! Patch in https://github.com/ostreedev/ostree/pull/2069.

**Pull request merged**
