### PR TITLE
tree-wide: Use autoptr for OstreeKernelArgs

### PR DESCRIPTION
**Pull request by cgwalters**
Much nicer looking.  Prep for more cleanup from
https://github.com/projectatomic/rpm-ostree/pull/1013

### CODE REVIEW

**Comment by cgwalters** [comment]
@rh-atomic-bot delegate=peterbaouoft

**Comment by peterbaouoft** [comment]
LGTM! Tho, I am currently on my phone and unable to see the test output, but I think it should be fine :).

@rh-atomic-bot r+ 29b37ae2

**Comment by jlebon** [comment]
@rh-atomic-bot r=peterbaouoft 8dbaafd

**Comment by cgwalters** [comment]
https://git.gnome.org/browse/gnome-desktop-testing/commit/?id=cdab3090b14a62253bd28b4e8c89297c021029e6

**Comment by peterbaouoft** [comment]
@rh-atomic-bot  retry

**Comment by peterbaouoft** [comment]
Wow, and is the fix above for gnome-desktop already merged? I am not quite familiar with the git gnome, but I think it should be ok once that fix is pushed :)

**Comment by jlebon** [comment]
@rh-atomic-bot r=peterbaouoft 81e4250

**Pull request closed without merging**
