### PR TITLE
async-progress: Plug memory leak while destroying GSource

### PR DESCRIPTION
**Pull request by uajain**
See https://gitlab.gnome.org/GNOME/glib/commit/71973c722

### CODE REVIEW

**Comment by uajain** [comment]
I found more `g_source_destroy()` calls in the code. Please hold off merging until I address them too.

Thanks.

**Comment by jlebon** [comment]
bot, add author to whitelist

**Comment by uajain** [comment]
/hold cancel

Ready for review

**Comment by jlebon** [comment]
Good catch, thanks for this!
/lgtm

**Comment by jlebon** [comment]
bot, retest this please

**Comment by jlebon** [comment]
> ```
> (ostree pull:31639): GLib-CRITICAL **: 16:05:25.964: g_source_destroy: assertion 'source != NULL' failed
> ```

/lgtm cancel

And after looking at this code for a while, I think the current code is actually correct (i.e. doesn't leak). Note that in `ensure_idle_queued` we're passing ownership to the context, so we really shouldn't be doing `g_source_unref` at all.

**Comment by jlebon** [comment]
Alternatively, to make things clearer, maybe we *should* keep a ref to it. So then it'd be something closer to what you have:

```diff
diff --git a/src/libostree/ostree-repo-pull.c b/src/libostree/ostree-repo-pull.c
index dd4dbff1..c85899b3 100644
--- a/src/libostree/ostree-repo-pull.c
+++ b/src/libostree/ostree-repo-pull.c
@@ -528,7 +528,8 @@ idle_worker (gpointer user_data)
   scan_data = g_queue_pop_head (&pull_data->scan_object_queue);
   if (!scan_data)
     {
-      g_clear_pointer (&pull_data->idle_src, (GDestroyNotify) g_source_destroy);
+      g_source_destroy (pull_data->idle_src);
+      g_clear_pointer (&pull_data->idle_src, (GDestroyNotify) g_source_unref);
       return G_SOURCE_REMOVE;
     }

@@ -556,7 +557,6 @@ ensure_idle_queued (OtPullData *pull_data)
   idle_src = g_idle_source_new ();
   g_source_set_callback (idle_src, idle_worker, pull_data, NULL);
   g_source_attach (idle_src, pull_data->main_context);
-  g_source_unref (idle_src);
   pull_data->idle_src = idle_src;
 }

@@ -4764,7 +4764,11 @@ ostree_repo_pull_with_options (OstreeRepo             *self,
   g_clear_pointer (&pull_data->pending_fetch_deltaparts, (GDestroyNotify) g_hash_table_unref);
   g_queue_foreach (&pull_data->scan_object_queue, (GFunc) scan_object_queue_data_free, NULL);
   g_queue_clear (&pull_data->scan_object_queue);
-  g_clear_pointer (&pull_data->idle_src, (GDestroyNotify) g_source_destroy);
+  if (pull_data->idle_src)
+    {
+      g_source_destroy (pull_data->idle_src);
+      g_clear_pointer (&pull_data->idle_src, (GDestroyNotify) g_source_unref);
+    }
   g_clear_pointer (&pull_data->dirs, (GDestroyNotify) g_ptr_array_unref);
   g_clear_pointer (&remote_config, (GDestroyNotify) g_key_file_unref);
   return ret;
```

**Comment by jlebon** [comment]
The hunk for `ostree_async_progress_finish` from this patch is good though! Can you just keep this one? I might just add a comment for the `ostree-repo-pull.c` bit in a separate PR to clarify things.

**Comment by uajain** [comment]
> The hunk for `ostree_async_progress_finish` from this patch is good though! Can you just keep this one? I might just add a comment for the `ostree-repo-pull.c` bit in a separate PR to clarify things.

Sounds good. Updated the PR.

**Comment by jlebon** [comment]
bot, retest this please

**Comment by uajain** [comment]
bot, retest this please

**Pull request merged**
