### PR TITLE
WIP: sysroot: Remove immutable bit from /etc/sysconfig/nfs

### PR DESCRIPTION
**Pull request by cgwalters**
Work around for https://src.fedoraproject.org/rpms/nfs-utils/pull-request/7
Currently Fedora-only.

### CODE REVIEW

**Comment by cgwalters** [comment]
Don't merge this - I'm just filing it here as a reference.  Will probably close this and just attach it as a patch to the Fedora ostree package.

**Comment by cgwalters** [comment]
Marking WIP so we don't merge, but I did test this patch.

**Comment by jlebon** [comment]
Looks OK to me as a Fedora patch.

**Comment by cgwalters** [comment]
https://koji.fedoraproject.org/koji/taskinfo?taskID=31958795

**Pull request closed without merging**
