### PR TITLE
ci: Add an "all options disabled" context

### PR DESCRIPTION
**Pull request by cgwalters**
We keep occasionally regressing this so let's start covering it now. I'm
intentionally not running the tests since that would likely entail a lot more
conditionalizing pain.

### CODE REVIEW

**Comment by jlebon** [comment]
bot, retest this please

**Comment by jlebon** [comment]
> checking for OT_DEP_CURL... yes
> configure: error: Curl enabled, but libsoup is not; libsoup is needed for tests
> ### EXITED WITH CODE 1 AFTER 138s

Hmm, it doesn't seem to be picking up the `--without-curl` properly.

**Comment by cgwalters** [comment]
OK, fixed ⬆️

**Comment by jlebon** [comment]
bot, retest this please

**Comment by jlebon** [comment]
@rh-atomic-bot r+ d3c0cbd

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
