### PR TITLE
contrib/golang: add more functions for commit

### PR DESCRIPTION
**Pull request by giuseppe**
I've added some more functions for being able to commits from Go
code.  Not all functions are exposed, but this is enough to commit a
directory.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by cgwalters** [comment]
Ah...I think we ended up moving this out into https://github.com/ostreedev/ostree-go right?  We should probably nuke `contrib/golang`.

**Comment by cgwalters** [comment]
(Or am I missing something?)

**Comment by giuseppe** [comment]
yes, I thought so.  Just when I tried ostree-go, I have not even managed to get it built so I was not sure about its status.  I'll try with that again.

**Comment by giuseppe** [comment]
@cgwalters, I've prepared a PR to rm -r the contrib directory:

https://github.com/ostreedev/ostree/pull/690

**Pull request closed without merging**
