### PR TITLE
ci: Add a Github Action for Rust for tests/inst

### PR DESCRIPTION
**Pull request by cgwalters**
Let's dip our toes in GH Actions (specifically aiming to migrate
away from Travis).

### CODE REVIEW

**Comment by lucab** [comment]
Great, thanks! Assuming https://github.com/ostreedev/ostree/pull/2302 goes in quickly, we can maybe directly turn on clippy here too.

**Comment by cgwalters** [comment]
Ahhh right, the plan to do clippy with this is going to fall over on our C dependencies.

**Review by kelvinfan001 — APPROVED** [review]
LGTM

**Pull request merged**
