### PR TITLE
app: Only remount /sysroot if needed

### PR DESCRIPTION
**Pull request by jlebon**
We should only try to remount `/sysroot` if we're actually handling the
sysroot repo and the repo isn't writable. We already have public APIs to
check each of those, so let's use them.

Closes: #2485

### CODE REVIEW

**Comment by kjbracey-arm** [comment]
I can confirm this patch fixes my script, applied to 2021.1.

**Review by cgwalters — APPROVED** [review]

**Comment by lucab** [comment]
I think this resulted in a change of behavior for a very specific CLI usecase.
rpm-ostree CI does some hackish manipulation via `ostree --repo /ostree/foo/bar`, which apparently was relying on the previous logic here to remount sysroot as RW.
I'm tying to amend the CI hacks in https://github.com/coreos/rpm-ostree/pull/3246, but I guess it would be nice to special case `--repo /ostree/...` and `--repo /sysroot/...` so that ostree automatically remounts `/sysroot`.
Or maybe there is a smarter way to do the detection via `vstatvfs()`?

**Comment by jlebon** [comment]
> I'm tying to amend the CI hacks in [coreos/rpm-ostree#3246](https://github.com/coreos/rpm-ostree/pull/3246), but I guess it would be nice to special case `--repo /ostree/...` and `--repo /sysroot/...` so that ostree automatically remounts `/sysroot`. Or maybe there is a smarter way to do the detection via `vstatvfs()`?

Hmm, maybe. I think this is somewhat specific to the rpm-ostree CI which likes to keep test repos in `/ostree/repo/` to ensure hardlinks with the sysroot repo. Maybe simplest is to have a hidden stamp file in `/run` somewhere and we just always remount rw in that case in this code? That way in the rpm-ostree CI, we'd just need a `touch /run/...` upfront.

Though if the only fallout is https://github.com/coreos/rpm-ostree/pull/3246, then I'd vote for not doing anything at all for now. :)

**Comment by lucab** [comment]
Yes I haven't seen any other fallout, at least yet.
I'm not super happy with the proliferation of magic stamp files as reliable interfaces for consumers.
Thinking a bit more about my previous copmment, the statfs approach would probably be to broad.
The rpm-ostree got easily fixed already.
Overall, I agree on:
 * keeping things as is going forward
 * if we notice further breakage for similar cases, just special-casing the /ostree path-prefixes

**Pull request merged**
