### PR TITLE
[merged] Strace cleanups

### PR DESCRIPTION
**Pull request by magcius**
Some simple changes I noticed while trying to debug ostree through strace. I don't think there's anything major in here, just some stuff to have less EBADF's and such.

### CODE REVIEW

**Comment by cgwalters** [comment]
bot, add author to whitelist

**Comment by cgwalters** [comment]
@rh-atomic-bot r+  f3b5662

**Comment by magcius** [comment]
It seems the test that failed is relying on the lockfile not getting unlinked, which I imagine is a mistake. But could you double-check?

**Comment by cgwalters** [comment]
Indeed, can you add
```
From 1b72a090a4fc2b21b1d3abd965ae423080490f98 Mon Sep 17 00:00:00 2001
From: Colin Walters <walters@verbum.org>
Date: Mon, 21 Nov 2016 21:01:25 -0500
Subject: [PATCH] fixup! ostree-repo: Make the lock with a long-lasting FD

---
 tests/test-admin-deploy-bootid-gc.sh | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/tests/test-admin-deploy-bootid-gc.sh b/tests/test-admin-deploy-bootid-gc.sh
index ba16f33..29360e3 100755
--- a/tests/test-admin-deploy-bootid-gc.sh
+++ b/tests/test-admin-deploy-bootid-gc.sh
@@ -51,7 +51,7 @@ fi
 newstagepath=$(ls -d sysroot/ostree/repo/tmp/staging-${NEW_TEST_BOOTID}-*)
 assert_has_dir "${newstagepath}"
 env OSTREE_BOOTID=${NEW_TEST_BOOTID} ${CMD_PREFIX} ostree admin deploy --karg=root=LABEL=MOO --karg=quiet --os=testos testos:testos/buildmaster/x86_64-runtime
-newstagepath=$(ls -d sysroot/ostree/repo/tmp/staging-${NEW_TEST_BOOTID}-*)
+newstagepath=$(echo sysroot/ostree/repo/tmp/staging-${NEW_TEST_BOOTID}-*)
 assert_not_has_dir "${stagepath}"
 assert_not_has_dir "${newstagepath}"
 
-- 
2.9.3
```

**Comment by magcius** [comment]
Fixed.

**Comment by cgwalters** [comment]
I think you pushed the wrong :no_good_man: commit.

**Comment by magcius** [comment]
Indeed. Pushed again now.

**Comment by cgwalters** [comment]
@rh-atomic-bot r+  2923e94

**Pull request closed without merging**
