### PR TITLE
rust: Update to gio 0.16

### PR DESCRIPTION
**Pull request by cgwalters**
This was quite seamless; the only thing I had to tweak was adding `+ Send` bounds in the `Box<dyn Error>` manual checksum_async API.

Closes: https://github.com/ostreedev/ostree/issues/2750

### CODE REVIEW

**Comment by lucab** [comment]
Since long time we had some mis-generation issues. Today I took some time to properly track it down and fixed it in https://github.com/gtk-rs/gir/pull/1403. For the moment though you'll have to keep carrying https://github.com/ostreedev/ostree/commit/6aa7d6e9f7f50654b6dc39568ad3f3066ebb910e in here.

**Comment by cgwalters** [comment]
Done, thanks!

**Comment by cgwalters** [comment]
OK passing CI here except for a flake (?) in the Ubutnu-latest in `test-concurrency.py`...did https://github.com/ostreedev/ostree/pull/2780

**Comment by lucab** [comment]
@cgwalters is https://github.com/gtk-rs/gtk-rs-core/pull/830 the whole fix for the docs-warning here or should we look further into it?

**Review by lucab — APPROVED** [review]

**Pull request merged**
