### PR TITLE
lib/bootloader: use ot_journal_print() instead of sd-journal

### PR DESCRIPTION
**Pull request by chergert**
This needs to use the helper so that USE_LIBSYSTEMD still works as
expected.

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]

**Comment by cgwalters** [comment]
Looks like we need an `#include <syslog.h>` - hmm, this seems to be indirectly pulled in in `ostree-sysroot-deploy.c` but I don't see where offhand (except indirectly via
```
#ifdef HAVE_LIBSYSTEMD
#include <systemd/sd-journal.h>
#endif
```
)

**Comment by chergert** [comment]
Is it worth adding an `#else` there to `#include <syslog.h>`?

**Comment by cgwalters** [comment]
> Is it worth adding an #else there to #include <syslog.h>?

SGTM (But I'd like to know how `ostree-sysroot-deploy.c` is compiling without that).  Or another way to say it is probably the better fix is to do these includes in `otutil.h` so they apply to all users of `ot_journal_send()` automatically.

**Comment by cgwalters** [comment]
/override continuous-integration/jenkins/pr-merge
Unrelated flake
/ok-to-test

**Pull request merged**
