### PR TITLE
docs: var/local -> var/usrlocal

### PR DESCRIPTION
**Pull request by elboulangero**
It seems to be a typo, please confirm, thanks!

### CODE REVIEW

**Comment by elboulangero** [comment]
However `/var/local` already exists, and according to https://www.tldp.org/LDP/sag/html/var-fs.html:

> **/var/local** Variable data for programs that are installed in /usr/local (i.e., programs that have been installed by the system administrator). Note that even locally installed programs should use the other /var directories if they are appropriate, e.g., /var/lock.

So maybe it's not a typo?

**Comment by jlebon** [comment]
> So maybe it's not a typo?

Right, as alluded to in the paragraph above, `/usr` is part of the deployment chroot and so will eventually be garbage collected as you upgrade. The `/usr/local` dir (and other dirs mentioned there) works around this by being a symlink to `/var/usrlocal` so that it persists across upgrades. HTH!

**Comment by elboulangero** [comment]
@jlebon Thanks for your reply.

What I meant is that the documentation suggests the following symlink:

    /usr/local → /var/local

Then just after the `tmpfiles.d` snippet creates directories in `var/usrlocal`. That's a bit of confusing, and it looks like one of them is a typo. Maybe the symlink above should be `/usr/local → /var/usrlocal`.

See https://github.com/ostreedev/ostree/blob/master/docs/manual/adapting-existing.md, sorry but I can't find a way to get a link to the exact line.

**Comment by cgwalters** [comment]
@elboulangero Can you redo the PR with that change?

**Comment by jlebon** [comment]
Ahh right, I see the mixup now. Thanks for bringing this up @elboulangero!

**Comment by elboulangero** [comment]
Thanks for your feedback, I updated the PR

**Comment by jlebon** [comment]
Thanks! @rh-atomic-bot r+ bdba5af

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
