### PR TITLE
libglnx: Bump to fix F28 compilation

### PR DESCRIPTION
**Pull request by jlebon**
Pull in https://github.com/GNOME/libglnx/pull/104 to fix compiling on
F28.

Update submodule: libglnx

### CODE REVIEW

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 91b5149

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Comment by jlebon** [comment]
OK, this is the restart flake.
@rh-atomic-bot retry

**Pull request closed without merging**
