### PR TITLE
[merged] Glnx round x

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Comment by cgwalters** [comment]
Oh fun, we were relying on `G_IO_ERROR` from vs `G_FILE_ERROR` from glib.  Will fix.

**Comment by cgwalters** [comment]
For clarity this depends on https://github.com/ostreedev/ostree/pull/317

**Comment by cgwalters** [comment]
Rebased :surfer: and now passes tests locally.

**Comment by jlebon** [comment]
:+1:
@rh-atomic-bot r+ 2aa48ae

**Pull request closed without merging**
