### PR TITLE
switchroot: Don't log if running as pid1, minor code style cleanups

### PR DESCRIPTION
**Pull request by cgwalters**
If we're running as pid1, avoid printing anything in the normal
success paths as we don't want to affect the physical console by
default; the device may be using a splash screen, etc.

Also cleanup the code a bit to use a single variable
`running_as_pid1`, declare-and-initialize, use the
`bool` type, etc.

### CODE REVIEW

**Comment by cgwalters** [comment]
@rh-atomic-bot delegate=akiernan

**Comment by jlebon** [comment]
This looks sane to me, though I'll give @akiernan a chance to look. CI failures look like Fedora mirror flakes.

**Comment by cgwalters** [comment]
> I consider the information printed quite helpful for debugging.

We do print when things *fail* still.  Have you found the prints useful in the success case?

**Comment by jlebon** [comment]
@rh-atomic-bot r+ c914b06

**Pull request closed without merging**
