### PR TITLE
[merged] Release 2016.9

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Comment by jlebon** [comment]
Could we wait until the mirrorlist PR gets in? Should be done testing very soon!

**Comment by cgwalters** [comment]
Hmm...I generally like to have major changes sit in git master for a little bit before we put them in a release.

**Comment by cgwalters** [comment]
We should be able to have a 2 week or so cadence for releases, so it shouldn't be long before we ship the mirrorlist bits.

**Comment by cgwalters** [comment]
Basically, I'd like to have this show up in CAHC for some manual testing too before updating fedora etc.

**Comment by jlebon** [comment]
Yup, that makes complete sense.
@rh-atomic-bot r+

**Pull request closed without merging**
