### PR TITLE
docs: Add GitHub Pages support

### PR DESCRIPTION
**Pull request by travier**
The goal here is to replace the manually updated readthedocs documentation website by an automatically updated website using GitHub Pages.

Preview: https://travier.github.io/ostree/
Fixes: https://github.com/ostreedev/ostree/issues/2206

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
Overall LGTM.

I think we may need to figure out how to change the readthedocs one to redirecto to this - basically hollow it out to just a link.  

The readthedocs link is first in a google search for me, so hopefully having it link will teach google to more quickly redirect.

**Comment by travier** [comment]
> I think we may need to figure out how to change the readthedocs one to redirecto to this - basically hollow it out to just a link.
> 
> The readthedocs link is first in a google search for me, so hopefully having it link will teach google to more quickly redirect.

I have unfortunately no idea how to do that as I have never used readthedocs before.

**Comment by cgwalters** [comment]
> I have unfortunately no idea how to do that as I have never used readthedocs before.

I think I can remember how to log in and then we should be able to point readthedocs at a `for-readthedocs` branch that has just a redirect.

**Comment by travier** [comment]
Maybe this could help: https://github.com/coreos/coreos.github.io/blob/master/index.html

**Comment by cgwalters** [comment]
/lgtm
Thanks for doing this!

**Comment by jlebon** [comment]
This looks really nice @travier!
/approve

**Comment by cgwalters** [comment]
> Enable GitHub pages for the master branch, with the docs folder as root.

I think that's done.

> Set the project URL to https://ostreedev.github.io/ostree/

What's "project URL"?  Trying to search for this it's too generic to find.

There seems to be...something...at https://ostreedev.github.io/ostree but it doesn't seem right :smile:

**Comment by travier** [comment]
Ping @cgwalters. It should be safe to switch the website URL now.

**Comment by jlebon** [comment]
Updated the project URL!

**Pull request merged**
