### PR TITLE
[merged] Minor cleanups

### PR DESCRIPTION
**Pull request by krnowak**
Just some small fixes like silencing a warning and others I spotted when building the project and skimming through some code.

### CODE REVIEW

**Comment by giuseppe** [comment]
bot, test pull request once

**Comment by giuseppe** [comment]
@krnowak .gitignore won't be overwritten if it is newer than Makefile.am.  You can verify that it is generated by changing the timestamp of the .gitignore file in the past (or rm'ing) it:

$ touch --date="2 years ago" apidoc/.gitignore && make
make[1]: Entering directory '/home/gscrivano/src/ostree/apidoc'
git.mk: Generating .gitignore

**Comment by krnowak** [comment]
Meh, ok, I think I'll drop the commit with changes in apidoc's .gitignore. I see you are using latest git.mk and the overrides files should be a part of the repo, otherwise gtk-doc is going to create an empty file - https://git.gnome.org/browse/gtk-doc/tree/gtkdoc-scan.in#n199

**Comment by krnowak** [comment]
Dropped for now.

**Comment by cgwalters** [comment]
@cgwalters-bot r+ 1a3ed55

**Pull request closed without merging**
