### PR TITLE
checkout: force writable directories with --user

### PR DESCRIPTION
**Pull request by giuseppe**
Otherwise an union checkout cannot create new files

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by cgwalters** [comment]
See https://github.com/ostreedev/ostree/issues/415
Currently it's possible to override on import with a filter function. Maybe something like:

```
diff --git a/src/libostree/ostree-repo.h b/src/libostree/ostree-repo.h
index ff1e712..f4f457d 100644
--- a/src/libostree/ostree-repo.h
+++ b/src/libostree/ostree-repo.h
@@ -531,11 +531,13 @@ typedef OstreeRepoCommitFilterResult (*OstreeRepoCommitFilter) (OstreeRepo    *r
  * @OSTREE_REPO_COMMIT_MODIFIER_FLAGS_NONE: No special flags
  * @OSTREE_REPO_COMMIT_MODIFIER_FLAGS_SKIP_XATTRS: Do not process extended attributes
  * @OSTREE_REPO_COMMIT_MODIFIER_FLAGS_GENERATE_SIZES: Generate size information.
+ * @OSTREE_REPO_COMMIT_MODIFIER_FLAGS_CANONICALIZE_PERMS: Ensure directories are writable by user, avoid world-writable files
  */
 typedef enum {
   OSTREE_REPO_COMMIT_MODIFIER_FLAGS_NONE = 0,
   OSTREE_REPO_COMMIT_MODIFIER_FLAGS_SKIP_XATTRS = (1 << 0),
-  OSTREE_REPO_COMMIT_MODIFIER_FLAGS_GENERATE_SIZES = (1 << 1)
+  OSTREE_REPO_COMMIT_MODIFIER_FLAGS_GENERATE_SIZES = (1 << 1),
+  OSTREE_REPO_COMMIT_MODIFIER_FLAGS_CANONICALIZE_PERMS = (1 << 2)
 } OstreeRepoCommitModifierFlags;
 
 /**
```
?

**Comment by giuseppe** [comment]
will that require a different commit/metadata for an user and a system image?  I thought about fixing the permissions here so that it will be possible to use the same data that is used for system images.

**Comment by cgwalters** [comment]
I'd suggest we also change system images.

**Comment by giuseppe** [comment]
something like this: https://github.com/projectatomic/atomic/pull/517 ?

I have tested it quickly here and it works for user checkouts as well

**Comment by cgwalters** [comment]
The reason I'm driving this towards the generalized "canonicalize permissions" issue is I think we also need to avoid world-writable files for example.  The only use case for a world-writable directory is `/tmp` with the sticky bit, and I'd suggest there in user mode checkouts we disable that.

(Really in general for containers we should be redirecting `/tmp` to e.g. `/tmp/containers/$ID or so)

**Comment by cgwalters** [comment]
Since that PR works, let's close this and possibly revisit #415 in another PR.

**Pull request closed without merging**
