### PR TITLE
Release 2018.8

### PR DESCRIPTION
**Pull request by cgwalters**
I'm about to go on vacation until Monday, but submitting this PR as a reminder to cut a release shortly after.  The remain-after-exit fix alone is important.

### CODE REVIEW

**Comment by cgwalters** [comment]
One side thing to investigate; at some point we switched from `/* No new symbols in yyyy.mm */` to 
```
LIBOSTREE_2018.1 {
} LIBOSTREE_2017.15;
```

Why was that?

**Comment by cgwalters** [comment]
Rebased :surfing_man: and lifting WIP.  Let's do a release.

**Comment by jlebon** [comment]
@rh-atomic-bot r+ 14f503b

**Comment by jlebon** [comment]
Fedora registry is currently down for maintenance: https://status.fedoraproject.org/.
I'm fine with just pushing `auto` to `master` for this if you'd rather not wait.

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
