### PR TITLE
main: print usage when no command given

### PR DESCRIPTION
**Pull request by jlebon**
Minor regression from #1106. We
want to print the usage text both when unknown commands are passed, as
well as when no commands are passed at all.

### CODE REVIEW

**Comment by cgwalters** [comment]
At this point let's add a test case?

**Comment by jlebon** [comment]
Fixed an existing related to this and added a check for it. ⬆️

**Comment by cgwalters** [comment]
Not worth rejigging for this, but WDYT about the commit topic style I've been using like `bin/commit` and `lib/commit` to distinguish?  In this case it'd be e.g. `bin/config: Tweak parameter string`.  (Also note at least I tend to capitalize the first word...though that is quite inconsistent even in the linux kernel commits)

@rh-atomic-bot r+ 41c6f98

**Comment by jlebon** [comment]
Yup, that makes sense to me re. `bin` vs `lib`. I usually don't capitalize messages, though I'll make an effort for this repo! :) Now let's see if the CI will play nice today.

@rh-atomic-bot retry

**Comment by cgwalters** [comment]
Looks like this fails `make syntax-check`

**Comment by jlebon** [comment]
OK, rebased and tweaked to adjust for https://github.com/ostreedev/ostree/pull/1123! ⬆️

**Comment by jlebon** [comment]
And reworded commit titles to match convention!

**Comment by jlebon** [comment]
>```
>++ grep --count '^Usage' err
>+ '[' 2 = 1 ']'
>```

Odd, that's definitely not the case.

```sh
$ ostree remote |& grep --count '^Usage'
1
```

Wonder if there's some weird race condition going on.

**Comment by cgwalters** [comment]
I've seen a race or two recently in at least the admin tests that I haven't tracked down.  But this one looks valid:

https://s3.amazonaws.com/aos-ci/ghprb/ostreedev/ostree/7f97c7440353ad5c955c13cf4e966594c462b196.3.1504903473009034131/output.log

**Comment by jlebon** [comment]
Heh, that was tricky. `ostree remote` only prints the help output twice when there's no system repo, which explains why I had trouble reproducing it. Fixup above! ⬆️

**Comment by cgwalters** [comment]
Ah, nice work!

@rh-atomic-bot r+ cc7fcda

**Comment by cgwalters** [comment]
Hmm...two new flakes?

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
