### PR TITLE
packaging/: Delete

### PR DESCRIPTION
**Pull request by cgwalters**
This is obsolete for a few reasons. The spec file is out of date (mostly the
%files, but also the BRs), and further down the line we'll need to use `make
dist` so we pick up vendored Rust sources. So the "git archive" approach won't
work for much longer anyways.

This came up in https://mail.gnome.org/archives/ostree-list/2017-February/msg00005.html

Basically, anyone who wants to build packages should look at the upstream
dist-git - until such time as e.g. Fedora learns to support pulling spec files
from upstream.

### CODE REVIEW

**Comment by giuseppe** [comment]
@rh-atomic-bot r+ 105023b

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
