### PR TITLE
lib: Split symbol versioning into -released and -devel

### PR DESCRIPTION
**Pull request by cgwalters**
So far a lot of submitted PR have added symbols into the first
section.  Split the file into `-released` and `-devel` to make
this more obvious.

To further enforce things, we hardcode a checksum of the `-released`
file in `test-symbols.sh`.  Only release commits should update that
checksum.

Did you notice I like checksums?

### CODE REVIEW

**Comment by cgwalters** [comment]
@rh-atomic-bot delegate=pwithnall

**Comment by pwithnall** [comment]
Looks good in theory, but in practice the CI is not happy:
```
Verifying all public symbols are documented:
+ sha256sum -c released-sha256.txt
ok documented symbols
sha256sum: WARNING: 1 computed checksum did NOT match
```

**Comment by cgwalters** [comment]
Hm, not quite sure how that happened.  Updated :arrow_up:

**Comment by pwithnall** [comment]
@rh-atomic-bot r+ a295280c1aa88d3ec26ce3d4fe2133ac434ec474

**Pull request closed without merging**
