### PR TITLE
build-sys: Post-release version bump

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Comment by cgwalters** [comment]
@pwithnall can you `r+` this to unblock other PRs?

**Comment by jlebon** [comment]
@rh-atomic-bot r+ eb05834

**Comment by pwithnall** [comment]
Drat, @jlebon got there first. No prize for me.

**Comment by jlebon** [comment]
:) @rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot r=pwithnall eb05834

**Pull request closed without merging**
