### PR TITLE
workflow/docs: Update to actions/checkout@v4 & dependabot: Update github-actions weekly

### PR DESCRIPTION
**Pull request by travier**
workflow/docs: Update to actions/checkout@v4

---

dependabot: Update github-actions weekly

### CODE REVIEW

**Comment by travier** [comment]
Note that the action that we're using to build the docs is deprecated: https://github.com/helaili/jekyll-action

That will be for a future PR.

**Comment by ericcurtin** [comment]
Hmmmm, what's the trick for this build "ci/prow/fcos-e2e" ?

**Review by ericcurtin — APPROVED** [review]

**Comment by cgwalters** [comment]
> Hmmmm, what's the trick for this build "ci/prow/fcos-e2e" ?

It doesn't run on doc-only changes, needs an
/override ci/prow/fcos-e2e

**Pull request merged**
