### PR TITLE
lib/repo: Port gpg signing function to new code style

### PR DESCRIPTION
**Pull request by cgwalters**
We already had all of the autocleanups ready for this.

### CODE REVIEW

**Comment by jlebon** [comment]
Nice! @rh-atomic-bot r+ c2eef2e

**Comment by cgwalters** [comment]
Let's have this one wait, it's not critical.

**Comment by cgwalters** [comment]
Let's have this one wait, it's not critical.

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
