### PR TITLE
tree-wide: Some glnx_fstatat() porting

### PR DESCRIPTION
**Pull request by cgwalters**
The new API is definitely nicer.

### CODE REVIEW

**Comment by jlebon** [comment]
You meant `glnx_fstatat_allow_noent` right? 🙃

**Comment by cgwalters** [comment]
Yep sorry pushed an old branch with the wrong script.  Depends on https://github.com/ostreedev/ostree/pull/1172

**Comment by cgwalters** [comment]
Rebased 🏄

**Comment by jlebon** [comment]
Nice! @rh-atomic-bot r+ 6331378

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
