### PR TITLE
Reload config

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Comment by cgwalters** [comment]
Prep patches in https://github.com/ostreedev/ostree/pull/661

**Comment by jlebon** [comment]
Hmm, there are other things that we'll probably need to add reload support for (e.g. [the repo config itself](https://github.com/ostreedev/ostree/issues/404)). Maybe we should call the function `ostree_repo_reload()` and add flags?

**Comment by cgwalters** [comment]
Rebased 🏄  And now reloads all of the config ✅

**Comment by jlebon** [comment]
Ouuhh very nice!

@rh-atomic-bot r+ 4801f64

**Pull request closed without merging**
