### PR TITLE
prepare-root: allow `sysroot.readonly=true` with kernel cmdline `ro`

### PR DESCRIPTION
**Pull request by ruihe774**
As described in #3315.

### CODE REVIEW

**Comment by cgwalters** [comment]
I'm not opposed to this, but I'd like to try a bit harder to reach another design where we can mount the root writable in the initramfs. Let's debate that in the issue https://github.com/ostreedev/ostree/issues/3315 I think to keep it in once place.

**Review by cgwalters — APPROVED** [review]

**Comment by ruihe774** [comment]
Does `MS_BIND | MS_REMOUNT` create readonly bind-mount for readonly source dir? If not, it is necessary to check `sysroot_currently_writable` and add `MS_RDONLY` when performing bind-mounts.

**Comment by ruihe774** [comment]
Are there test cases that cover things in initramfs? I think I'd better add some tests to prevent regression. Especially, I have not played with root_transient, etc_transient, and using_composefs yet.

**Comment by cgwalters** [comment]
> Ok. It just works. Feel free to merge it.

Yeah, bind mounts will inherit the writability by default.

> Are there test cases that cover things in initramfs? I think I'd better add some tests to prevent regression. 

There's definitely a coverage gap in some cases; we only test some of this implicitly. I've been meaning to try to make it easier to run ostree-prepare-root outside of a proper initramfs (and boot process), testing it as a container which would dramatically simplify complexity for testing.

> Especially, I have not tried ro with root_transient, etc_transient, and using_composefs yet.

I think though your use case in the future is going to be better addressed by adding integrity and measurement at the OS level and not trying to enforce it via drive-specific writability - which gets into the composefs path specifically so we'd effectively be obsoleting the case of "ro with composefs we mount writable later" for example.

**Comment by ruihe774** [comment]
Thx

**Pull request merged**
