### PR TITLE
lib: Adjust comments in symbols section for last release

### PR DESCRIPTION
**Pull request by cgwalters**
2017.1 was released, move its section above the line.

### CODE REVIEW

**Comment by giuseppe** [comment]
@rh-atomic-bot r+

**Comment by jlebon** [comment]
@giuseppe Try specifying the hash as well.
See: https://github.com/servo/homu/issues/86
Will be fixed once we rebase homu to the latest version.

**Comment by cgwalters** [comment]
@rh-atomic-bot r=giuseppe 1127c06

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 1127c06

**Comment by jlebon** [comment]
@rh-atomic-bot r+ 1127c06

**Comment by jlebon** [comment]
Oh whoops, I hadn't refreshed the page :)

**Pull request closed without merging**
