### PR TITLE
[merged] Ci sanitize

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Comment by cgwalters** [comment]
Ok, seeing the same metalink issue here.  I was debugging this locally but failing to get a useful core.  Will try again.

**Comment by cgwalters** [comment]
Found it, should be good to go :racehorse:

**Comment by jlebon** [comment]
Nice!
@rh-atomic-bot r+ 8887c63

**Comment by cgwalters** [comment]
@jlebon see :scream_cat: :arrow_up:

**Comment by jlebon** [comment]
Ahhh, silly GitHub UI.
@rh-atomic-bot r+ ab75b68

**Pull request closed without merging**
