### PR TITLE
Allow building without libsoup

### PR DESCRIPTION
**Pull request by OYTIS**
Signed-off-by: Anton Gerasimov <anton.gerasimov@openmailbox.org>

### CODE REVIEW

**Comment by OYTIS** [comment]
This is more for discussion than for immediate merger as is. I understand there was probably a good reason to fail in this case, but there are also use cases (like my favourite embedded one) where tests don't matter much and additional dependencies do. Maybe there could be another configure parameter (`--without-soup-please` or something) for such cases.

**Comment by OYTIS** [comment]
That would be great, thank you.

**Comment by cgwalters** [comment]
OK, updated :arrow_up: - look good to you?

**Comment by OYTIS** [comment]
Looks good, thank you.

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 1383812

**Pull request closed without merging**
