### PR TITLE
Release 2021.1

### PR DESCRIPTION
**Pull request by cgwalters**
Release 2021.1

---

configure: post-release version bump

---

### CODE REVIEW

**Comment by cgwalters** [comment]
Following https://github.com/ostreedev/ostree/issues/2307

**Comment by cgwalters** [comment]
(Will make a hackmd.io doc for release notes on Monday)

**Review by jlebon — APPROVED** [review]
Hmm, GitHub Action for release commit sanity check is assuming it has a `config.h` even though it's not building the tree.

CoreOS CI was failing on the openat issue. I restarted it now that https://github.com/ostreedev/ostree/pull/2306 was merged.

**Comment by cgwalters** [comment]
> Hmm, GitHub Action for release commit sanity check is assuming it has a config.h even though it's not building the tree.

Yeah, I think that was ported to GH actions from the old CI but without testing it.

**Pull request merged**
