### PR TITLE
_ostree_ensure_fsverity: Properly check for errors

### PR DESCRIPTION
**Pull request by alexlarsson**
If fs_verity_wanted == _OSTREE_FEATURE_YES we should fail if !suported, but we were checking !supported where supported is a pointer, not a boolean. This caused us to miss errors when the kernel didn't support fs-verity that lead to lots of debugging.

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
LGTM. 

(Another one where Rust wouldn’t have let this happen)

**Comment by ericcurtin** [comment]
Could be a good C/C++ compiler warning/error addition that you could turn on optionally, ensure pointers get checked against NULL in C or nullptr in C++ and that booleans get checked against true/false etc. For new C or C++ codebases to switch on from the start.

**Review by ericcurtin — APPROVED** [review]

**Comment by ericcurtin** [comment]
Tagging @davidmalcolm in case it gives inspiration to a feature (although I'm sure this kinda check has been discussed many times before)

**Comment by ericcurtin** [comment]
I guess the header files from libraries might make these warnings difficult among other things :sweat_smile:

**Pull request merged**
