### PR TITLE
tests/repo-finder: Run realpath() on /tmp

### PR DESCRIPTION
**Pull request by cgwalters**
This fixes running this test case inside
https://github.com/cgwalters/coretoolbox

### CODE REVIEW

**Comment by jlebon** [comment]
Hmm, where was the test failing? Are we not handling symlinks correctly somewhere else?

**Comment by cgwalters** [comment]
> Hmm, where was the test failing? 

The test serializes file paths to strings, and something in the GLib stack was effectively doing `realpath`, so we need them to match.

**Comment by jlebon** [comment]
bot, retest this please

**Comment by jlebon** [comment]
```
tests/test-repo-finder-mount.c:448:          g_error ("Unknown result ‘%s’ with keyring ‘%s’.",
maint.mk: found error message ending in period
```

**Comment by jlebon** [comment]
/lgtm

Known flakes:
/override f29-primary
/override continuous-integration/travis-ci/pr

And this one I think we need to adjust the test deps or just bump to a newer tag. Clearly not related to this patch though.
/override f29-rpmostree

**Pull request merged**
