### PR TITLE
lib/kargs: add missing function to symbol-versioning table

### PR DESCRIPTION
**Pull request by r4f4**
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

### CODE REVIEW

**Comment by r4f4** [comment]
See https://github.com/projectatomic/rpm-ostree/issues/1862#issuecomment-507629189

**Comment by cgwalters** [comment]
bot, add author to whitelist

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 25917e5

(Side note, hmm, looks like recent gpg changes broke older Debian/Ubuntu)

**Comment by jlebon** [comment]
Also need it in `ostree-sections.txt` to satisfy `test-symbols.sh`

**Comment by jlebon** [comment]
@rh-atomic-bot r+ 35a4f2c

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
