### PR TITLE
main: Make ostree --version output YAML (and add gitrev)

### PR DESCRIPTION
**Pull request by cgwalters**
I learned today that `docker version` does this and I really like
the idea.  While we have the patient open, also add the gitrev
with code taken from https://github.com/projectatomic/rpm-ostree/pull/584

### CODE REVIEW

**Comment by cgwalters** [comment]
```
$ ./ostree --version
libostree:
 Version: 2017.2
 Git: v2017.2-10-gd5a1222452e92c6f0c45696ef355d61193f54b17
 Features:
  - libcurl
  - libsoup
  - gpgme
  - libarchive
  - selinux
  - libmount
```

**Comment by cgwalters** [comment]
Okay, so I have absolutely no idea right now why https://github.com/ostreedev/ostree/pull/691/commits/48ef1054dd82635e6f5a0d268261b90461782ea5 fixed the tests 😕  I added that to debug it, since it passed locally.

But anyways let's ignore that!  This should be good to go.

**Comment by giuseppe** [comment]
I think "grep -q" exits as soon as it gets one occurrence as it doesn't really care how many there are, so causing an EPIPE in ostree.  It would probably work with "grep '- gpgme' > /dev/null".

Anyway, I think it is cleaner with a temporary file:

@rh-atomic-bot r+ 5df79df

**Comment by cgwalters** [comment]
Ah right of course, and `-o pipefail` comes into play here.  That's like the second time I've forgotten about it and spent a while debugging in as many months.

**Pull request closed without merging**
