### PR TITLE
[merged] refs: Fix a logic error

### PR DESCRIPTION
**Pull request by Mathnerd314**
I encountered the "Opening remotes/ dir" error while I was working with some broken pull code, and this fixed it. But it's an independent change.

### CODE REVIEW

**Comment by cgwalters** [comment]
What was the broken pull code?  I believe there's a bug here...I'm trying to better understand what it is though.
Is there a simple test case for this?

So previously we threw if the remote dir didn't exist.  Now if `errno == ENOENT && rev == NULL` (i.e. we're trying to delete a ref)...okay, I see now, we ignore trying to delete a ref for a nonexistent remote.

Ah, but confusingly...the `refs` builtin papers over this because it enumerates existing ones when doing a match, so we can't actually test this via the command line.

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ 6e66b8e

**Comment by cgwalters** [comment]
For posterity the outstanding diff I had trying to write a test:

```
diff --git a/tests/basic-test.sh b/tests/basic-test.sh
index 003df89..f3bafae 100755
--- a/tests/basic-test.sh
+++ b/tests/basic-test.sh
@@ -19,7 +19,7 @@
 
 set -euo pipefail
 
-echo "1..57"
+echo "1..58"
 
 $OSTREE checkout test2 checkout-test2
 echo "ok checkout"
@@ -265,6 +265,14 @@ ${CMD_PREFIX} ostree --repo=repo3 rev-parse aremote/test2
 echo "ok pull-local with --remote arg"
 
 cd ${test_tmpdir}
+${CMD_PREFIX} ostree --repo=repo3 rev-parse aremote:test2
+${CMD_PREFIX} ostree --repo=repo3 refs --delete aremote:test2
+${CMD_PREFIX} ostree --repo=repo3 refs --delete aremote:test2
+rm repo3/refs/remotes/aremote -rf
+${CMD_PREFIX} ostree --repo=repo3 refs --delete aremote:test2
+echo "ok refs --delete for a remote"
+
+cd ${test_tmpdir}
 ${CMD_PREFIX} ostree --repo=repo3 prune
 find repo3/objects -name '*.commit' > objlist-before-prune
 rm repo3/refs/heads/* repo3/refs/remotes/* -rf
```

**Comment by Mathnerd314** [comment]
I guess there could be a C API test that imported ostree-repo-private.h. But that seems like overkill.

**Comment by Mathnerd314** [comment]
For reference, the issue with the pull code was that I didn't increment the outstanding requests, so it finished early (before fetching the ref's commit) and thus tried to write a non-existent ref.

**Pull request closed without merging**
