### PR TITLE
[merged] Update libglnx for O_TMPFILE build time option

### PR DESCRIPTION
**Pull request by cgwalters**
See: https://github.com/ostreedev/ostree/issues/421

### CODE REVIEW

**Comment by cgwalters** [comment]
@rh-atomic-bot delegate=gatispaeglis

**Comment by gatispaeglis** [comment]
If I run ./autogen.sh, it does not contain "yes/no" for O_TMPFILE:

```
OSTree 2016.7
    ===============


    introspection:                                yes
    rofiles-fuse:                                 yes
    libsoup (retrieve remote HTTP repositories):  yes
    libsoup TLS client certs:                     yes
    SELinux:                                      yes
    systemd:                                      yes
    libmount:                                     yes
    libarchive (parse tar files directly):        yes
    static deltas:                                yes (always enabled now)
    O_TMPFILE:                                    
    man pages (xsltproc):                         yes
    api docs (gtk-doc):                           no
    gjs-based tests:                              yes
    dracut:                                       no
    mkinitcpio:                                   no
    grub2-mkconfig path:                          grub2-mkconfig
```

**Comment by cgwalters** [comment]
Did you `git submodule update --init` ?

**Comment by gatispaeglis** [comment]
I did:

git clone git@github.com:ostreedev/ostree.git 
cd ostree
curl https://patch-diff.githubusercontent.com/raw/ostreedev/ostree/pull/426.patch | git apply - 
./autogen.sh

Then git submodule update --init is not necessary.

**Comment by cgwalters** [comment]
It looks like `git apply -` isn't updating the submodule for some reason.  Also I think things are a little strange if you do things in that order from a fresh clone, because `autogen.sh` will itself do `git submodule update --init`.  But we really want the submodule initialized before.

This works for me:

```
git clone git@github.com:ostreedev/ostree.git && cd ostree   # optional - you can use an existing checkout
git pull https://github.com/cgwalters/ostree.git update-libglnx-otmpfile
git submodule update --init
```

**Comment by cgwalters** [comment]
In general with submodules I often use `git submodule status` and verify the commits are what I expect them to be.

**Comment by gatispaeglis** [comment]
Ah, ok. Now it works :)

@rh-atomic-bot r+ aa0dbf7

**Pull request closed without merging**
