### PR TITLE
main/commit: Rework control flow to use --tree=X path

### PR DESCRIPTION
**Pull request by cgwalters**
Rework the simple cases of "commit ." and "commit argv[1]" to
generate the more general "--tree=X --tree=Y" path, so that we
only have one primary control flow here.

Prep for a future patch around loading SELinux policy from
the first argument.

### CODE REVIEW

**Comment by jlebon** [comment]
OK yup. This is much easier to review with whitespace changes ignored.
/lgtm

**Comment by cgwalters** [comment]
/hold
needs CI fixes from https://github.com/ostreedev/ostree/pull/2040

**Comment by cgwalters** [comment]
/override continuous-integration/travis-ci/pr
test-pull-repeated flake

**Pull request merged**
