### PR TITLE
Switch to external composefs

### PR DESCRIPTION
**Pull request by cgwalters**
Since there's now a stable shared library, let's use it.

### CODE REVIEW

**Review by ericcurtin — APPROVED** [review]

**Comment by cgwalters** [comment]
I've belatedly realized that not having composefs shipped in current c9s is going to make this more logistically complicated.  I think that will likely happen, but hard to say when.

**Comment by alexlarsson** [comment]
Yeah, for practical reason, maybe hold off on this a bit.

**Comment by cgwalters** [comment]
OK composefs is in c9s, rebased :surfer:

**Review by alexlarsson — APPROVED** [review]

**Comment by cgwalters** [comment]
Yeah, various CI failures because our build/runtime deps come from packaging and that breaks when dropping in new binaries.  I did <https://src.fedoraproject.org/rpms/ostree/c/b64d73f3718115cb9d6926275e21f5b16c3f14f9?branch=rawhide> as one fix.

**Comment by cgwalters** [comment]
Ah, this needs https://github.com/coreos/fedora-coreos-config/pull/2900 at least

**Pull request merged**
