### PR TITLE
ci: Bump flatpak build to F28

### PR DESCRIPTION
**Pull request by mwleeds**

### CODE REVIEW

**Comment by alexlarsson** [comment]
I finally got flatpak moved to f28 in https://github.com/flatpak/flatpak/pull/1741

**Comment by mwleeds** [comment]
@alexlarsson that's on the master branch though. So we either need to backport those commits to the stable branch or switch the ostree CI from the stable branch to master. The latter is what this branch already does but I'm not sure if it's actually desired.

**Comment by mwleeds** [comment]
bot, retest this please

**Comment by cgwalters** [comment]
Fine by me to use master for now, if we run into trouble we can change it.

@rh-atomic-bot r+ 0f83e2b

**Comment by mwleeds** [comment]
I deleted the outdated comments in `ci/flatpak.sh` so this needs re-approval

**Comment by jlebon** [comment]
Looks like a bunch of the failures were due to missing py2. I pushed a fixup with a line we were missing from flatpak's CI (though we could probably just call out to *its* `build.sh`).

**Comment by jlebon** [comment]
@rh-atomic-bot r+ 80e60d2

**Comment by jlebon** [comment]
@rh-atomic-bot r+ 6d34c14

**Pull request closed without merging**
