### PR TITLE
lib/fetcher: Allow clients to append to User-Agent

### PR DESCRIPTION
**Pull request by jlebon**
We do already have `http-headers`, which potentially could be used to
allow clients to completely override the field, but it seems like the
more common use case is simply to append.

### CODE REVIEW

**Comment by jlebon** [comment]
Leaving WIP for feedback before adding tests.

**Comment by alexlarsson** [comment]
Looks good to me.

**Comment by cgwalters** [comment]
Looks sane to me too.

**Comment by jlebon** [comment]
Dropped WIP and added tests! :arrow_up:

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ a13bb36

**Pull request closed without merging**
