### PR TITLE
Update libglnx submodule

### PR DESCRIPTION
**Pull request by smcv**
Resolves: https://gitlab.gnome.org/GNOME/libglnx/-/issues/3

---

This resolves half of #2525 (#2529 is the other half).

```diff
diff --git a/glnx-fdio.c b/glnx-fdio.c
index 3fa73b5..fb57280 100644
--- a/glnx-fdio.c
+++ b/glnx-fdio.c
@@ -829,7 +829,7 @@ glnx_regfile_copy_bytes (int fdf, int fdt, off_t max_bytes)
                   have_cfr = 0;
                   try_cfr = false;
                 }
-              else if (G_IN_SET (errno, EXDEV, EOPNOTSUPP))
+              else if (G_IN_SET (errno, EXDEV, EINVAL, EOPNOTSUPP))
                 /* We won't try cfr again for this run, but let's be
                  * conservative and not mark it as available/unavailable until
                  * we know for sure.
```

Thanks to @oleid for the patch.

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]

**Comment by cgwalters** [comment]
Ah sorry, our CI requires a magic comment in the commit message to avoid accidental submodule reverts.  

```
[2022-01-28T12:22:58.733Z] error: Commit message for a938a9304d2d698e2df2111a2b3ea6bf38819cf5 changes a submodule, but does not match regex Update submodule: libglnx
```

**Comment by smcv** [comment]
`continuous-integration/jenkins/pr-merge` seems to be failing, but I don't know whether that's a regression. I would be quite surprised if this PR broke it.

**Comment by cgwalters** [comment]
/override continuous-integration/jenkins/pr-merge 

Yeah, this is some sort of new flake it seems, but I can't find the actual error yet.

**Pull request merged**
