### PR TITLE
Add a --finders option to find-remotes

### PR DESCRIPTION
**Pull request by mwleeds**
Endless' OBS build of ostree stopped working when we started compiling with Avahi; hence this PR.

### CODE REVIEW

**Comment by mwleeds** [comment]
Just found another thing to fix, one minute

**Comment by mwleeds** [comment]
Wait, the duplicate detection doesn't seem to be working

**Comment by mwleeds** [comment]
Alright, now I think it's ready

**Comment by mwleeds** [comment]
@cgwalters FYI this is something we're trying to get into our upcoming release of Endless planned for Monday.

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ ecf757d

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ ecf757d

**Pull request closed without merging**
