### PR TITLE
build-sys: post-release version bump

### PR DESCRIPTION
**Pull request by cgwalters**
Per request by flatpak.

### CODE REVIEW

**Comment by dustymabe** [comment]
is there some way to know that this is basically a 'dev version' since we havn't released `.7` yet?

**Comment by cgwalters** [comment]
(I mean yes, kind of `ostree --version` might help with that but the exact semantics there get murky and I'd like to know exactly what would be using that and why)

**Comment by alexlarsson** [comment]
I don't think any released software should rely on an unreleased ostree version.
However, its very nice to have a check during development that at least you need an unstable version.
Obviously the ostree unstable version could change abi or we add api several times, but at least its better than nothing.

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+ 70118ed

**Pull request closed without merging**
