### PR TITLE
Libglnx rebump + UBSAN

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Comment by cgwalters** [comment]
@jlebon Looks like this flaked on libsoup, but can we get this in?  The libglnx reversion is annoying for working on other PRs.

**Comment by jlebon** [comment]
@rh-atomic-bot r+ ecf92ee

**Comment by jlebon** [comment]
Hmm something seems wonky here. Both the PR tester and the merge test failed with:

```
ERROR: test-libglnx-xattrs
==========================

# random seed: R02S0999b2ad448ec413da6a0156fe79fa42
timeout: the monitored command dumped core
./buildutil/tap-test: line 26:  6195 Illegal instruction     timeout --kill-after=60 --signal=ABRT $(( 600 * ${TEST_TIMEOUT_FACTOR:-1} )) ${srcd}/${bn} -k --tap
1..1
ERROR: test-libglnx-xattrs - too few tests run (expected 1, got 0)
ERROR: test-libglnx-xattrs - exited with status 132 (terminated by signal 4?)
```

Could there still be some undefined behaviour the new flag is catching?

**Comment by cgwalters** [comment]
https://github.com/GNOME/libglnx/pull/35

**Comment by cgwalters** [comment]
Rebased 🏄

**Comment by jlebon** [comment]
@rh-atomic-bot r+ 4229920

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
