### PR TITLE
bootloader/zipl: Run in target deployment as container if needed

### PR DESCRIPTION
**Pull request by cgwalters**
sysroot: Expose deployment container executor internally

Prep for using this for zipl.

---

bootloader/zipl: Run in target deployment as container if needed

xref https://issues.redhat.com/browse/MGMT-16303

Basically the OCP Assisted installer has now grown code
to try to do OS updates offline post-install, and this means
we need to handle the case of running zipl from the target
root.

---

### CODE REVIEW

**Comment by cgwalters** [comment]
cc @nikita-dubrovskii

**Comment by cgwalters** [comment]
OK with this I get:

```
(ostree admin undeploy:120445): OSTree-DEBUG: 20:29:15.365: executing zipl in deployment root
Error: Config file '/lib/s390-tools/zipl.conf': Cannot build automenu: no IPL entries available
Looking for components in '/lib/s390-tools'
Using config file '/lib/s390-tools/zipl.conf'
error: Final bootloader swap: Child process exited with code 1
```

Which...hmm, looks like it's saying no BLS entries were found?

**Comment by cgwalters** [comment]
OK, we now correctly bind `/boot`, and this appears to work as far as successfully running `zipl`!

**Review by nikita-dubrovskii — APPROVED** [review]
LGTM, thx for this!

**Comment by jmarrero** [comment]
```
   CCLD     ostree
/usr/bin/ld: ./.libs/libostree-1.so: undefined reference to `_ostree_sysroot_run_in_deployment'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:4466: ostree] Error 1
make[2]: Leaving directory '/__w/ostree/ostree'
make[1]: *** [Makefile:8202: all-recursive] Error 1
make[1]: Leaving directory '/__w/ostree/ostree'
make: *** [Makefile:3345: all] Error 2
Error: Process completed with exit code 2.
```
failure seems legit re-running just in case.

**Comment by cgwalters** [comment]
Should be fixed, let's see

**Review by jmarrero — APPROVED** [review]
lgtm

**Pull request merged**
