### PR TITLE
admin: status - correctly check GPG signature

### PR DESCRIPTION
**Pull request by r4f4**
Closes: #1770

### CODE REVIEW

**Comment by jlebon** [comment]
bot, add author to whitelist

**Comment by jlebon** [comment]
Looks good to me! Just a random note: for the commit message, something more consistent like this would be nice: `admin/status: Correctly check GPG signature`. Would be good too to add a test for this (or just tweak an existing one)? Maybe in `admin-test.sh`?

**Comment by cgwalters** [comment]
> Would be good too to add a test for this (or just tweak an existing one)? Maybe in admin-test.sh?

AFAICS we don't have any admin tests that use gpg, I didn't want to make adding one a prereq for a new contributor, so I said on IRC it'd be OK without.

**Comment by jlebon** [comment]
Yup sure, that's fine. @r4f4 mind just tweaking the commit msg?

**Comment by r4f4** [comment]
@jlebon Done. Thank you for reviewing.

**Comment by dustymabe** [comment]
nice work @r4f4!

**Pull request closed without merging**
