### PR TITLE
ot-fs-utils.c: try $TMPDIR if /var/tmp fails

### PR DESCRIPTION
**Pull request by 9999years**
In `ot_map_anonymous_tmpfile_from_content` we call `libglnx`'s [`glnx_open_anonymous_tmpfile`][glnx_open_anonymous_tmpfile] function, which attempts to create an fd in `/var/tmp` regardless of the value of `$TMPDIR`.

This is _usually_ okay, but can fail in some contexts, such as in the [NixOS][1] build environment, which doesn't have `/var` mapped at all.

To avoid failing in this case, if `glnx_open_anonymous_tmpfile` fails, we retrieve the value of `$TMPDIR` manually and try calling `glnx_open_anonymous_tmpfile_full` directly (which is equivalent to `glnx_open_anonymous_tmpfile` save for allowing us to choose the directory the fd is created in).

[1]: https://nixos.org/
[glnx_open_anonymous_tmpfile]: https://gitlab.gnome.org/GNOME/libglnx/-/blob/7e3a19958e6af94b764c772a58adf47e6cc4b678/glnx-fdio.c#L305-318

### CODE REVIEW

**Comment by cgwalters** [comment]
Hi, thank you for the patch!

This seems like something better fixed in libglnx though, right?  The git for that is here: https://gitlab.gnome.org/GNOME/libglnx
Not opposed to a workaround here though similar to this.

**Comment by 9999years** [comment]
Opened [libglnx#20](https://gitlab.gnome.org/GNOME/libglnx/-/merge_requests/20).

**Comment by cgwalters** [comment]
Closing this since we have https://gitlab.gnome.org/GNOME/libglnx/-/merge_requests/20 merged and I believe that fully covers this.  (if that's not correct please reopen).  Thanks again!

**Comment by 9999years** [comment]
Mind cutting a new release so we can downstream this?

**Comment by cgwalters** [comment]
> Mind cutting a new release so we can downstream this?

Somewhat soon, there's a few things that need a bit more work before that I think.

That said: https://github.com/ostreedev/ostree/pull/2208 bumps the submodule, and feel free to cherry pick that libglnx patch downstream if you like.  To get it to apply what I've done in the past is use e.g. `git format-patch -1` on the libglnx commit, then manually edit the diff and change it to `a/libglnx/foo.c` instead of just `a/foo.c`, then it can be applied at the toplevel.

**Pull request closed without merging**
